#!/bin/bash
set -e

# Glasswatch One-Command Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/jmckinley/glasswatch/main/install.sh | bash

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BOLD}${BLUE}"
echo "  ╔═══════════════════════════════════╗"
echo "  ║         Glasswatch Installer      ║"
echo "  ║   AI-Driven Patch Management      ║"
echo "  ╚═══════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo -e "${RED}✗ $1 is required but not installed.${NC}"
        echo "  Install it from: $2"
        exit 1
    else
        echo -e "${GREEN}✓ $1 found${NC}"
    fi
}

echo -e "\n${BOLD}Checking prerequisites...${NC}"
check_command docker "https://docs.docker.com/get-docker/"
# Support both "docker compose" (v2) and "docker-compose" (v1)
if ! docker compose version &> /dev/null 2>&1; then
    if ! command -v docker-compose &> /dev/null; then
        echo -e "${RED}✗ docker compose is required but not installed.${NC}"
        echo "  Install it from: https://docs.docker.com/compose/install/"
        exit 1
    fi
    COMPOSE_CMD="docker-compose"
else
    COMPOSE_CMD="docker compose"
fi
echo -e "${GREEN}✓ docker compose found${NC}"
check_command curl "https://curl.se/"

# Generate secrets
SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")

# Collect API keys
echo -e "\n${BOLD}API Key Setup${NC}"
echo -e "${YELLOW}Glasswatch uses a few external services. Enter your keys now or press Enter to skip (you can add them later in .env).${NC}\n"

echo -e "${BOLD}1. Anthropic API Key${NC} (required for AI assistant and NLP rule creation)"
echo -e "   Get yours at: ${BLUE}https://console.anthropic.com/settings/keys${NC}"
read -p "   ANTHROPIC_API_KEY (or press Enter to skip): " ANTHROPIC_API_KEY

echo -e "\n${BOLD}2. Resend API Key${NC} (required for invite emails, weekly digest, alerts)"
echo -e "   Get yours at: ${BLUE}https://resend.com/api-keys${NC}"
echo -e "   ${YELLOW}Note: also verify your sender domain in Resend dashboard${NC}"
read -p "   RESEND_API_KEY (or press Enter to skip): " RESEND_API_KEY
if [ -n "$RESEND_API_KEY" ]; then
  read -p "   RESEND_FROM_EMAIL (e.g. alerts@yourdomain.com): " RESEND_FROM_EMAIL
  RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-"noreply@glasswatch.io"}
fi

echo -e "\n${BOLD}3. Sentry DSN${NC} (optional — error tracking, highly recommended for production)"
echo -e "   Get yours at: ${BLUE}https://sentry.io/settings/ → Projects → DSN${NC}"
read -p "   SENTRY_DSN (or press Enter to skip): " SENTRY_DSN

echo -e "\n${BOLD}4. Scanner API Keys${NC} (add whichever scanners you use — can be added later)"
echo -e "   ${YELLOW}Tenable:${NC} Settings → My Account → API Keys at ${BLUE}https://cloud.tenable.com${NC}"
read -p "   TENABLE_ACCESS_KEY (or press Enter to skip): " TENABLE_ACCESS_KEY
if [ -n "$TENABLE_ACCESS_KEY" ]; then
  read -p "   TENABLE_SECRET_KEY: " TENABLE_SECRET_KEY
fi
echo -e "   ${YELLOW}Qualys:${NC} API URL + credentials from your Qualys subscription"
read -p "   QUALYS_USERNAME (or press Enter to skip): " QUALYS_USERNAME
if [ -n "$QUALYS_USERNAME" ]; then
  read -s -p "   QUALYS_PASSWORD: " QUALYS_PASSWORD; echo
  read -p "   QUALYS_API_URL (e.g. https://qualysapi.qualys.com): " QUALYS_API_URL
fi
echo -e "   ${YELLOW}Rapid7:${NC} InsightVM → Administration → API Keys"
read -p "   RAPID7_HOST (e.g. https://your-instance.insight.rapid7.com, or press Enter to skip): " RAPID7_HOST
if [ -n "$RAPID7_HOST" ]; then
  read -p "   RAPID7_API_KEY: " RAPID7_API_KEY
fi

# Create directory
INSTALL_DIR="${GLASSWATCH_DIR:-./glasswatch}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo -e "\n${BOLD}Generating configuration...${NC}"

# Write .env
cat > .env << EOF
# Glasswatch Configuration
# Generated by installer on $(date)

SECRET_KEY=${SECRET_KEY}
ENV=production
DEBUG=false

# Database (managed by Docker Compose)
DATABASE_URL=postgresql+asyncpg://glasswatch:${POSTGRES_PASSWORD}@postgres:5432/glasswatch
SYNC_DATABASE_URL=postgresql://glasswatch:${POSTGRES_PASSWORD}@postgres:5432/glasswatch
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis (managed by Docker Compose)
REDIS_URL=redis://redis:6379/0

# Frontend URL (update if using a custom domain)
FRONTEND_URL=http://localhost:3000
BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]

# Auth tokens
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Email via Resend (invite emails, weekly digest, alerts)
# Get your key: https://resend.com/api-keys
RESEND_API_KEY=${RESEND_API_KEY:-}
RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-noreply@glasswatch.io}

# Anthropic AI (AI assistant, NLP rule creation)
# Get your key: https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

# Scanner integrations (add keys for the scanners you use)
# Tenable: https://cloud.tenable.com -> Settings -> API Keys
TENABLE_ACCESS_KEY=${TENABLE_ACCESS_KEY:-}
TENABLE_SECRET_KEY=${TENABLE_SECRET_KEY:-}
# Qualys: your subscription credentials
QUALYS_USERNAME=${QUALYS_USERNAME:-}
QUALYS_PASSWORD=${QUALYS_PASSWORD:-}
QUALYS_API_URL=${QUALYS_API_URL:-}
# Rapid7: InsightVM -> Administration -> API Keys
RAPID7_HOST=${RAPID7_HOST:-}
RAPID7_API_KEY=${RAPID7_API_KEY:-}

# OAuth (optional - Google/GitHub login)
# Google: https://console.cloud.google.com -> APIs -> Credentials
# GitHub: https://github.com/settings/developers
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=

# Error tracking (highly recommended for production)
# Get your DSN: https://sentry.io/settings/ -> Projects -> DSN
SENTRY_DSN=${SENTRY_DSN:-}
EOF

echo -e "${GREEN}✓ .env generated${NC}"

# Write docker-compose.yml
cat > docker-compose.yml << 'COMPOSE'
version: '3.9'

services:
  backend:
    image: ghcr.io/jmckinley/glasswatch-backend:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_DATABASE_URL=${SYNC_DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - TENABLE_ACCESS_KEY=${TENABLE_ACCESS_KEY:-}
      - TENABLE_SECRET_KEY=${TENABLE_SECRET_KEY:-}
      - QUALYS_USERNAME=${QUALYS_USERNAME:-}
      - QUALYS_PASSWORD=${QUALYS_PASSWORD:-}
      - QUALYS_API_URL=${QUALYS_API_URL:-}
      - RAPID7_HOST=${RAPID7_HOST:-}
      - RAPID7_API_KEY=${RAPID7_API_KEY:-}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/jmckinley/glasswatch-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN:-}
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=glasswatch
      - POSTGRES_USER=glasswatch
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glasswatch"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
COMPOSE

echo -e "${GREEN}✓ docker-compose.yml generated${NC}"

# Pull images
echo -e "\n${BOLD}Pulling images (this may take a minute)...${NC}"
$COMPOSE_CMD pull

# Start services
echo -e "\n${BOLD}Starting Glasswatch...${NC}"
$COMPOSE_CMD up -d

# Wait for backend health
echo -e "\n${BOLD}Waiting for services to be ready...${NC}"
max_attempts=30
attempt=0
while [ $attempt -lt $max_attempts ]; do
    if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
        break
    fi
    attempt=$((attempt + 1))
    echo -n "."
    sleep 2
done

if [ $attempt -eq $max_attempts ]; then
    echo -e "\n${YELLOW}⚠ Backend didn't respond in time. Check logs with: $COMPOSE_CMD logs backend${NC}"
else
    echo -e "\n${GREEN}✓ Backend is healthy${NC}"
fi

# Run migrations
echo -e "\n${BOLD}Running database migrations...${NC}"
$COMPOSE_CMD exec -T backend alembic upgrade head
echo -e "${GREEN}✓ Migrations complete${NC}"

# Seed demo data
echo -e "\n${BOLD}Loading demo data...${NC}"
$COMPOSE_CMD exec -T backend python3 -c "
import sys
sys.path.insert(0, '/app')
from backend.scripts.seed_demo import main as seed_main
seed_main()
" 2>/dev/null && echo -e "${GREEN}✓ Demo data loaded${NC}" || echo -e "${YELLOW}⚠ Demo seed skipped (non-fatal)${NC}"

echo -e "\n${BOLD}${GREEN}╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║   Glasswatch is ready!                ║${NC}"
echo -e "${BOLD}${GREEN}╚═══════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Frontend:${NC}  http://localhost:3000"
echo -e "  ${BOLD}API:${NC}       http://localhost:8000"
echo -e "  ${BOLD}API Docs:${NC}  http://localhost:8000/docs"
echo ""
echo -e "  ${BOLD}Login:${NC} Click \"Try Demo\" for instant access"
echo -e "         Or create an account at http://localhost:3000/login"
echo ""
echo -e "  ${BOLD}Manage:${NC}"
echo -e "    Stop:    $COMPOSE_CMD down"
echo -e "    Logs:    $COMPOSE_CMD logs -f"
echo -e "    Update:  $COMPOSE_CMD pull && $COMPOSE_CMD up -d"
echo ""
echo -e "  ${BOLD}Config:${NC} Edit .env then restart: $COMPOSE_CMD up -d"
echo ""

# Show configuration status
echo -e "${BOLD}Configuration Status:${NC}"
if [ -n "${ANTHROPIC_API_KEY}" ]; then
  echo -e "  ${GREEN}✓ AI assistant${NC} — enabled"
else
  echo -e "  ${YELLOW}○ AI assistant${NC} — disabled (add ANTHROPIC_API_KEY to .env)"
  echo -e "    → https://console.anthropic.com/settings/keys"
fi
if [ -n "${RESEND_API_KEY}" ]; then
  echo -e "  ${GREEN}✓ Email (Resend)${NC} — enabled (invite emails, weekly digest)"
else
  echo -e "  ${YELLOW}○ Email${NC} — disabled (add RESEND_API_KEY to .env)"
  echo -e "    → https://resend.com/api-keys"
fi
if [ -n "${SENTRY_DSN}" ]; then
  echo -e "  ${GREEN}✓ Error tracking${NC} — enabled (Sentry)"
else
  echo -e "  ${YELLOW}○ Error tracking${NC} — not configured (add SENTRY_DSN to .env)"
  echo -e "    → https://sentry.io (free tier available)"
fi
if [ -n "${TENABLE_ACCESS_KEY}" ] || [ -n "${QUALYS_USERNAME}" ] || [ -n "${RAPID7_HOST}" ]; then
  echo -e "  ${GREEN}✓ Scanner integration${NC} — configured"
else
  echo -e "  ${YELLOW}○ Scanner integration${NC} — not configured (add scanner keys to .env)"
  echo -e "    → Or use CSV import at http://localhost:3000/import"
fi
echo ""
